### ISSUE TITLE
Is this project unmaintained?

### ISSUE THREAD

**Issue by ghost** [jmorag/kakoune.el#5]
Before I switch to Kakoune for coding, I am a big (evil)Emacs user.
I still need Emacs for org-mode but I would love to have unified experience across two text-editors.

I found kakoune.el which is quite awesome. Its features are more than enough for me as it is.
I'm thinking about adding some features when I improve my Elisp skills.
Now, I am just curious whether @jmorag is still using this package?

**Comment by jmorag** [comment]
I still use it every day (except on days when I don't open touch my computer, which aren't too many). I haven't been pushing any code to it because I'm not missing any functionally. You can see my full config here https://github.com/jmorag/.emacs.d. 

If you have any extra features you'd like to implement I'll happily accept PRs :)

**Comment by ghost** [comment]
I see! Thanks for your full config.
I wil probably spend time groking it first and see if I can do anything. :)
