### ISSUE TITLE
kakoune-setup-keybinds ,  ryo-modal and :mc-all

### ISSUE THREAD

**Issue by ratish-punnoose** [jmorag/kakoune.el#7]
It seems that the line in kakoune-setup-keybinds that calls ryo-modal-major-mode-keys fails.
The error seems to point to the :mc-all keyword  handling within ryo-modal-major-mode-keys.
Note: the following call to ryo-modal-keys with the :mc-all works.

I have the version of ryo-modal from elpa which looks like the current master branch of ryo-modal.
Are you using a forked version of ryo-modal that has a fix for this?

**Comment by jmorag** [comment]
The only reason I forked ryo-modal in my own config was to take out the logic for changing cursor color, which wasn't working for me. Otherwise, it doesn't have any fixes. 

Can you point to the exact line number in question? It looks like `:mc-all` is only applied to a call to `ryo-modal-keys` at https://github.com/jmorag/kakoune.el/blob/master/kakoune.el#L51 and not on any calls to `ryo-modal-major-mode-keys`.

**Comment by ratish-punnoose** [comment]
Thank you for responding, yes that is indeed the line.I think this is a ryo-modal problem that a kakoune one (I get an error by using the ryo-modal call directly with the :mc-all). It is just that the kakoune-setup-binds calls the ryo-modal with the :mc-all, so if I can't use that function directly.  Instead I used a copy of that function with the ryo-modal-keys call stripped out.

**Comment by Kungsgeten** [comment]
The `mc-all` keyword should work on the latest MELPA version. Not sure if you're using MELPA Stable though since I usually do not tag new versions.

**Comment by jmorag** [comment]
Just merged the latest ryo-modal commit into my fork and it is indeed working. Thank you @Kungsgeten!

**Comment by jmorag** [comment]
Closing this since the problem seems to be solved. Feel free to reopen if it persists.
